config/routes.rb
Movietime::Application.routes.draw do
  get "users/new"

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  get "users/new"
  match '/signup', to: 'users#new'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def  full_title(page_title)
    base_title = "MovieTime"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
  <a href="#">MovieTime</a>
  by Vedant Bhatt
</small>
<nav>
  <ul>
    <li><%= link_to "About",   about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>

  </ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <%= link_to "MOVIETIME", '#', id: "logo" %>
    <ul class="nav">
      <li class="divider-vertical"></li>
      <li class="active"><%= link_to "Home", root_path %></li>
      <li class="divider-vertical"></li>
      <li class="active"><%= link_to "About Us", about_path %> </li>
      <li class="divider-vertical"></li>
      <li class="active"><%= link_to "Contact Us", contact_path %></li>
      <li class="divider-vertical"></li>
      <li class="active"><%= link_to "Sign In", "#" %></li>
    </ul>
    <form class="navbar-search pull-right">
      <input type="text" class="search-query" placeholder="Search">
    </form>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>

<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About Us</h1>
<p>
  About Us
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>

<h1>Contact Us</h1>
<p>
  Contact Us
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>
  To get Help contact us at 1212121212
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit" style="background-image: url(http://static.myopera.com/community/graphics/speeddials/Opera-Background-Space-Harmonica.jpg)">
   <h1 style="color: white;">Welcome to MovieTime</h1>
   <h2>Write a review for the movies you like and dislike!!</h2>

  <%= link_to "Sign Up!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<div>
  <ul class="thumbnails">

    <li class="span4">
      <div class="thumbnails">
      <a href="#" class="thumbnail">
        <%= link_to image_tag("Avengers.jpg", height:270, alt: "Avengers"), '#' %>
      </a>
      <h3>Avengers</h3>
      <p>Thumbnail caption</p>
      <button class="btn btn-medium">Read More</button>
      </div>
    </li>
    <li class="span4">
      <div class="thumbnails">
      <a href="#" class="thumbnail">
        <%= link_to image_tag("perks of being a wallflower.jpg", height: 270, width:300, alt: "Perks of Being a Wallflower"), '#' %>
      </a>
      <h3>The Perks of being a Wallflower</h3>
      <p>Thumbnail caption</p>
      <button class="btn btn-medium">Read More</button>
      </div>
    </li>
    <li class="span4">
      <div class="thumbnails">
      <a href="#" class="thumbnail">
        <%= link_to image_tag("The bourne legacy.jpg", width: 300, height:270, alt:"Bourne Legacy") %>
      </a>
      <h3>The Bourne Legacy</h3>
      <p>Thumbnail caption</p>
      <button class="btn btn-medium">Read More</button>
      </div>
    </li>
    <li class="span4">
      <div class="thumbnails">
    <a href="#" class="thumbnail">
      <%= link_to image_tag("The-Dark-Knight-Rises-teaser.jpg", width: 280, height:270, alt: "") %>
    </a>
    <h3>The Dark Knight Rises</h3>
    <p>Thumbnail caption</p>
    <button class="btn btn-medium">Read More</button>
          </div>
    </li>
  </ul>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>